JAVA VERSION CHECK CHANGE and small changes

diff --git a/install/installer/traf_config_check b/install/installer/traf_config_check
--- a/install/installer/traf_config_check
+++ b/install/installer/traf_config_check
@@ -399,91 +399,42 @@ if [[ -z "$JAVA_HOME" ]]; then
    echo "***ERROR: JAVA_HOME variable not set in config file." >> $ERROR_LOG   
 else
 
-   REQ_VER="1.7.0_65" 
-   JAVA7="7"
-   JAVA8="8"
-   JAVA65="65"
    error=""
-
-   for node in $NODE_LIST
-   do
-      THIS_JVM_VER="$(ssh -q -n $node $JAVA_HOME/bin/java -version 2>&1 > /dev/null)"
-      if [[ "$THIS_JVM_VER" == *"No such file"* ]]; then
-         errorFound=1
+   REQ_VER="1.7.0_65"
+   #Only checking on 1 node for now. This will change.
+   if [[ "$JAVA_8_SUPPORT" == "Y" ]]; then
+      $PWD/checkJava8.py 
+      if [[ $? != 0 ]]; then
          error=1
-         echo "JAVA HOME" >> $ERROR_LOG
-         echo "***ERROR: Unable to find Java version on node $node" >> $ERROR_LOG
-         echo "***ERROR: Must enter a specific Java version (example: /usr/java/jdk1.7.0_67)"  >> $ERROR_LOG
-         echo "***ERROR: Please check for typos and that directory exists"  >> $ERROR_LOG
-         
-      fi      
-    done
+      fi
+   else
+      $PWD/checkJava.py
+      if [[ $? != 0 ]]; then
+         error=1
+      fi
+   fi
 
-    if [[ -z $error ]]; then 
-       for node in $NODE_LIST
-       do
-         javaType="$(ssh -q -n $node $JAVA_HOME/bin/javac -version 2>&1 > /dev/null | grep "No such file" | wc -l)"
-         if [[ $javaType -eq "1" ]]; then
-            errorFound=1
-            echo "JAVA HOME" >> $ERROR_LOG
-            echo "***ERROR: Java version on node $node is of type JRE"  >> $ERROR_LOG
-            echo "***ERROR: Java version needed on all nodes must be a JDK"  >> $ERROR_LOG
-         fi
 
-         temp_JAVA=`echo "${THIS_JVM_VER:15:2}" | sed 's/.*\.//'`
+   if [[ -n $error ]]; then
+       errorFound=1
+       echo "JAVA HOME" >> $ERROR_LOG
+       if [[ "$JAVA_8_SUPPORT" == "Y" ]]; then
+          #Get used to this error. You are going to see it alot. 
+          echo "***ERROR: Your existing JAVA_HOME is not JAVA 8"  >> $ERROR_LOG
+          echo "***ERROR: Required java version is JAVA 8, any other version is not supported"  >> $ERROR_LOG 
+       else
+          echo "***ERROR: Your existing JAVA_HOME is less than $REQ_VER"  >> $ERROR_LOG
+          echo "***ERROR: Required java version should be greater than $REQ_VER"  >> $ERROR_LOG
+       fi
+  fi
+    
 
-         #Check if using something less than Java 7
-         if [[ "$temp_JAVA" -lt "$JAVA7" ]]; then
-            error="true"
-         fi
-
-         if [[ "$JAVA_8_SUPPORT" == "Y" ]]; then
-            if [[ "$temp_JAVA" -ne "$JAVA8" ]]; then
-               error="true"
-            fi
-
-         fi
-
-         #Checking if using 1.7.0_n
-         if [[ "${THIS_JVM_VER:18:1}" -eq "0" ]] && [[ "$temp_JAVA" -eq "$JAVA7" ]]; then
-            if [[ "${THIS_JVM_VER:20:1}" -eq "0" ]] || [[ "${THIS_JVM_VER:20:2}" -lt $JAVA65 ]]; then
-               #If Java is **less** than than 1.7.0_65 the next command will fail.
-               #Install will fail anyways if less than 1.7.0_65
-               #Will not fail if Java is 1.7.0_100 or greater
-               #Temporary fix to support Java 7 upgrades greater than 100
-               if [[ "${THIS_JVM_VER:20:3}" -lt $JAVA_65 ]]; then
-                  error="true"
-               fi
-            fi
-         fi
-
-         if [[ -n $error ]]; then
-            errorFound=1
-            echo "JAVA HOME" >> $ERROR_LOG
-            if [[ "$JAVA_8_SUPPORT" == "Y" ]]; then
-               #Get used to this error. You are going to see it alot. 
-               echo "***ERROR: Your existing JAVA_HOME on $node is not JAVA 8"  >> $ERROR_LOG
-               echo "***ERROR: Your Java Version on $node = $THIS_JVM_VER"  >> $ERROR_LOG
-               echo "***ERROR: Required java version is JAVA 8, any other version is not supported"  >> $ERROR_LOG 
-            else
-               echo "***ERROR: Your existing JAVA_HOME on $node is less than $REQ_VER"  >> $ERROR_LOG
-               echo "***ERROR: Your Java Version on $node = $THIS_JVM_VER"  >> $ERROR_LOG
-               echo "***ERROR: Required java version on $node should be greater than $REQ_VER"  >> $ERROR_LOG
-            fi
-         fi
-       done
-    fi
-    hadoopPath="$HADOOP_PATH"
-    hadoopBinPath="$HADOOP_BIN_PATH"
-
-    export PATH="$JAVA_HOME/bin:$PATH"
-    sudo chmod 777 $TRAF_CONFIG
-    sed -i '/PATH\=/d' $TRAF_CONFIG
-    echo "export PATH=\"$PATH\"" >>$TRAF_CONFIG
-    echo "export HADOOP_BIN_PATH=\"$hadoopBinPath\"" >>$TRAF_CONFIG
-    echo "export HADOOP_PATH=\"$hadoopPath\"" >>$TRAF_CONFIG
-    sudo chmod 777 $TRAF_CONFIG
-    source $TRAF_CONFIG
+   export PATH="$JAVA_HOME/bin:$PATH"
+   sudo chmod 777 $TRAF_CONFIG
+   sed -i '/\<PATH\>\=/d' $TRAF_CONFIG
+   echo "export PATH=\"$PATH\"" >>$TRAF_CONFIG
+   sudo chmod 777 $TRAF_CONFIG
+   source $TRAF_CONFIG
 fi
 
 }
