Adding latest Trafodion changes and esgynDB_install

diff --git a/install/installer/trafodion_install b/install/installer/trafodion_install
--- a/install/installer/trafodion_install
+++ b/install/installer/trafodion_install
@@ -105,14 +105,6 @@ while [[ $# -gt 0 ]]; do
     shift
 done
 
-
-#==============================================
-echo
-echo "******************************"
-echo " TRAFODION INSTALLATION START"
-echo "******************************"
-echo
-
 #==============================================
 # Default values
 
@@ -236,6 +228,15 @@ else
 fi
 
 source $TRAF_CONFIG
+
+#Need to set CLUSTERNAME for DCS
+if [[ $node_count -ne 1 ]]; then
+   sudo chmod 777 $TRAF_CONFIG
+   sed -i '/CLUSTERNAME\=/d' $TRAF_CONFIG
+   echo "export CLUSTERNAME=\"$CLUSTER_NAME\"" >> $TRAF_CONFIG
+   sudo chmod 777 $TRAF_CONFIG
+   source $TRAF_CONFIG
+fi
 if [ $? -ne 0 ]; then
    echo "***ERROR: unable to source $TRAF_CONFIG"
    exit -1
@@ -312,13 +313,6 @@ fi
 
 sed -i '/ACCEPT_LICENSE\=/d' $TRAF_CONFIG
 echo "export ACCEPT_LICENSE=\"$ACCEPT_LICENSE\"" >> $TRAF_CONFIG
-
-#=============================================
-#license checking
-$LOCAL_WORKDIR/licensecheck $LOCAL_WORKDIR
-if [ $? -eq 1 ]; then
-  exit 1
-fi
 
 #==============================================
 # untar package and files into /usr/lib/trafodion (the new TRAF_WORKDIR)
@@ -420,8 +414,15 @@ if [[ -n "$USER_CONFIG" ]]; then
          tar -xzf $TRAF_BUILD $install_features_path
          source $install_features_path
          echo "export CDH_5_3_HDP_2_2_SUPPORT=\"$CDH_5_3_HDP_2_2_SUPPORT\"" >> $TRAF_CONFIG
+          if [[ -z $CDH_5_4_SUPPORT ]]; then
+             echo "export CDH_5_4_SUPPORT=\"N\"" >> $LOCAL_TRAF_CONFIG
+          else
+             echo "export CDH_5_4_SUPPORT=\"$CDH_5_4_SUPPORT\"" >> $LOCAL_TRAF_CONFIG
+          fi
       else
          CDH_5_3_HDP_2_2_SUPPORT="N"
+         CDH_5_4_SUPPORT="N"
+         echo "export CDH_5_4_SUPPORT=\"$CDH_5_4_SUPPORT\"" >> $TRAF_CONFIG
          echo "export CDH_5_3_HDP_2_2_SUPPORT=\"$CDH_5_3_HDP_2_2_SUPPORT\"" >> $TRAF_CONFIG
       fi
    fi
@@ -456,10 +457,18 @@ do
       fi
       if [[ $HADOOP_TYPE == "cloudera" ]]; then
          if [[ $CDH_5_3_HDP_2_2_SUPPORT == "N" ]]; then
-            supportedHBase=$(echo $version | grep "0.98.1" | wc -l)
-            if [[ $supportedHBase -eq "0" ]]; then
-               echo "***ERROR: HBase installed must be 0.98.1 on node $node"
-               exit -1
+            if [[ $CDH_5_4_SUPPORT == "Y" ]]; then
+               supportedHBase=$(echo $version | grep "1.0.0" | wc -l)
+               if [[ $supportedHBase -eq "0" ]]; then
+                  echo "***ERROR: HBase installed must be 1.0.0 on node $node"
+                  exit -1
+               fi
+            else 
+               supportedHBase=$(echo $version | grep "0.98.1" | wc -l)
+               if [[ $supportedHBase -eq "0" ]]; then
+                  echo "***ERROR: HBase installed must be 0.98.1 on node $node"
+                  exit -1
+               fi
             fi
          else
             supportedHBase=$(echo $version | grep "0.98.6" | wc -l)
@@ -468,11 +477,6 @@ do
                exit -1
             fi
          fi
-      fi
-      hbaseVersion=$(echo "${version#*.}"| cut -f1 -d".")
-      if [[ $hbaseVersion -lt "98" ]]; then
-         echo "***ERROR: HBase installed must be 0.98"
-         exit -1
       fi
       hbaseVersion=$(ssh -q -n $node grep "Version" $HOME/hbaseVersion.txt | sed 's/-.*//' | awk {'print$2'})
       break
@@ -581,10 +585,33 @@ echo "******************************"
 echo
 
 if [[ "$UPGRADE_TRAF" == "true" ]]; then
-
-   echo "***INFO: $TRAF_USER username has already been installed." | tee -a $INSTALL_LOG
-   echo "***INFO: Skipping Trafodion setup..." | tee -a $INSTALL_LOG
-
+   sudo chmod 777 $HOME_DIR/$TRAF_USER/.bashrc
+   sudo sed -i -e "s@export NODE_LIST=.*@export NODE_LIST=\"$NODE_LIST\"@" $HOME_DIR/$TRAF_USER/.bashrc   
+   sudo sed -i -e "s@export MY_NODES=.*@export MY_NODES=\"$MY_NODES\"@" $HOME_DIR/$TRAF_USER/.bashrc
+   
+   for node in $NODE_LIST
+   do
+      userForTrafodion=$(ssh -q -n $node grep "$TRAF_USER:" /etc/passwd | wc -l)
+      if [[ "$userForTrafodion" == 0 ]]; then
+         $LOCAL_WORKDIR/traf_setup | tee -a $INSTALL_LOG
+         if [ ${PIPESTATUS[0]} != "0" ]; then
+            echo "***ERROR: Error while running traf_setup." | tee -a $INSTALL_LOG
+            echo "***ERROR: Setup not complete, review logs." | tee -a $INSTALL_LOG
+            echo "***ERROR: Exiting...." | tee -a $INSTALL_LOG
+            exit -1
+         else
+            echo "***INFO: Trafodion environment setup completed" | tee -a $INSTALL_LOG
+         fi
+      else
+         echo "***INFO: Installing required RPM packages" | tee -a $INSTALL_LOG
+         $LOCAL_WORKDIR/traf_package_setup | tee -a $INSTALL_LOG
+         if [ $? != 0 ]; then
+            echo "***ERROR: Unable to create Trafodion userid: $TRAF_USER"
+            exit -1
+         fi
+      fi
+   done  
+   
 else
    $LOCAL_WORKDIR/traf_setup | tee -a $INSTALL_LOG
 
@@ -614,15 +641,11 @@ if [ $node_count -ne 1 ]; then
 fi
 
 
-#Create sqconfig file if it does not exist
-
-if [[ ! -f $HOME_DIR/$TRAF_USER/sqconfig ]]; then
-   $LOCAL_WORKDIR/traf_sqconfig
-   if [ $? != 0 ]; then
-      echo "***ERROR: traf_sqconfig script failed."
-      echo "***ERROR: sqconfig file not created."
-      exit -1
-   fi
+$LOCAL_WORKDIR/traf_sqconfig
+if [ $? != 0 ]; then
+   echo "***ERROR: traf_sqconfig script failed."
+   echo "***ERROR: sqconfig file not created."
+   exit -1
 fi
 #Reserve DCS Ports
 
@@ -635,21 +658,25 @@ do
    redhatSystem=$(ssh -q -n $node '/sbin/sysctl net.ipv4.ip_local_reserved_ports | wc -l')
    if [[ "$redhatSystem" -ge "1" ]]; then
       reserved_ports=$(ssh -q -n $node '/sbin/sysctl net.ipv4.ip_local_reserved_ports' | awk -F'=' '{print $2;}' | sed 's/^ //')
-      ssh -q -n $node 'sudo chmod 777 /etc/sysctl.conf'
-      ssh -q -n $node 'sudo sed -i '/net.ipv4.ip_local_reserved_ports""\=*/d' /etc/sysctl.conf'
+      ssh -q -n $node 'sudo chmod 777 /etc/sysctl.conf' 2>&1 > /dev/null
+      ssh -q -n $node 'sudo sed -i '/net.ipv4.ip_local_reserved_ports""\=*/d' /etc/sysctl.conf' 2>&1 > /dev/null
 
    if [[ -z "${reserved_ports}" ]]; then
-      ssh -q -n $node "sudo echo "$reservedTrafodionPorts" >> /etc/sysctl.conf"
+      ssh -q -n $node "sudo echo "$reservedTrafodionPorts" >> /etc/sysctl.conf" 2>&1 > /dev/null
    else
-      ssh -q -n $node "sudo echo "$reservedTrafodionPorts","$reserved_ports" >> /etc/sysctl.conf"
+      ssh -q -n $node "sudo echo "$reservedTrafodionPorts","$reserved_ports" >> /etc/sysctl.conf" 2>&1 > /dev/null
    fi
-   ssh -q -n $node 'sudo chmod 644 /etc/sysctl.conf'
+   ssh -q -n $node 'sudo chmod 644 /etc/sysctl.conf' 2>&1 > /dev/null
    ssh -q -n $node 'sudo /sbin/sysctl -p' 2>&1 > /dev/null
    else
       echo "***ERROR: Unable to reserve DCS ports (${trafodion_ports})."
       exit -1
    fi
 done
+
+#Set Max kernel pid 
+
+$TRAF_PDSH sudo sysctl -w kernel.pid_max=65535 2>&1 > /dev/null
 
 
 #Create install directory
