Back up restore changes and bug fixes

diff --git a/install/installer/traf_cloudera_mods98 b/install/installer/traf_cloudera_mods98
--- a/install/installer/traf_cloudera_mods98
+++ b/install/installer/traf_cloudera_mods98
@@ -31,6 +31,8 @@ source $TRAF_CONFIG
 export PDSH="pdsh -R exec"
 export PDSH_SSH_CMD="ssh -q -n %h"
 export PDCP="pdcp -R ssh"
+export PDSH_HADOOP_NODES="$PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD"
+export PDCP_HADOOP_NODES="$PDCP $MY_HADOOP_NODES"
 #=====================================
 # copy Trafodion trx jar to Cloudera's plugins directory on all nodes
 
@@ -72,23 +74,23 @@ fi
 echo "***INFO: copying $hbase_trx_jar to all nodes"
 if [ $node_count -ne 1 ]; then
     
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo rm -rf $HADOOP_PATH/hbase-trx* 2>/dev/null
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo rm -rf /usr/lib/hbase/lib/hbase-trx* 2>/dev/null
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo rm -rf /usr/share/cmf/lib/plugins/hbase-trx* 2>/dev/null
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo rm -rf /usr/lib/hbase/lib/trafodion* 2>/dev/null
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo rm -rf /usr/share/cmf/lib/plugins/trafodion* 2>/dev/null
-    $PDSH $MY_NODES $PDSH_SSH_CMD mkdir -p $LOCAL_WORKDIR 2>/dev/null
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD mkdir -p $LOCAL_WORKDIR 2>/dev/null
+    $PDSH_HADOOP_NODES sudo rm -rf $HADOOP_PATH/hbase-trx* 2>/dev/null
+    $PDSH_HADOOP_NODES sudo rm -rf /usr/lib/hbase/lib/hbase-trx* 2>/dev/null
+    $PDSH_HADOOP_NODES sudo rm -rf /usr/share/cmf/lib/plugins/hbase-trx* 2>/dev/null
+    $PDSH_HADOOP_NODES sudo rm -rf /usr/lib/hbase/lib/trafodion* 2>/dev/null
+    $PDSH_HADOOP_NODES sudo rm -rf /usr/share/cmf/lib/plugins/trafodion* 2>/dev/null
+    $TRAF_PDSH mkdir -p $LOCAL_WORKDIR 2>/dev/null
+    $PDSH_HADOOP_NODES mkdir -p $LOCAL_WORKDIR 2>/dev/null
     cp $UNTAR_DIR/export/lib/$hbase_trx_jar $LOCAL_WORKDIR
     cp $UNTAR_DIR/export/lib/$traf_util_jar $LOCAL_WORKDIR
-    $PDCP $MY_HADOOP_NODES $LOCAL_WORKDIR/$hbase_trx_jar $LOCAL_WORKDIR
-    $PDCP $MY_HADOOP_NODES $LOCAL_WORKDIR/$traf_util_jar $LOCAL_WORKDIR
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo cp $LOCAL_WORKDIR/$hbase_trx_jar $HADOOP_PATH
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo cp $LOCAL_WORKDIR/$traf_util_jar $HADOOP_PATH
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo chmod 644 $HADOOP_PATH/$hbase_trx_jar
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo chmod 644 $HADOOP_PATH/$traf_util_jar
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD rm $LOCAL_WORKDIR/$hbase_trx_jar 2>/dev/null
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD rm $LOCAL_WORKDIR/$traf_util_jar 2>/dev/null
+    $PDCP_HADOOP_NODES $LOCAL_WORKDIR/$hbase_trx_jar $LOCAL_WORKDIR
+    $PDCP_HADOOP_NODES $LOCAL_WORKDIR/$traf_util_jar $LOCAL_WORKDIR
+    $PDSH_HADOOP_NODES sudo cp $LOCAL_WORKDIR/$hbase_trx_jar $HADOOP_PATH
+    $PDSH_HADOOP_NODES sudo cp $LOCAL_WORKDIR/$traf_util_jar $HADOOP_PATH
+    $PDSH_HADOOP_NODES sudo chmod 644 $HADOOP_PATH/$hbase_trx_jar
+    $PDSH_HADOOP_NODES sudo chmod 644 $HADOOP_PATH/$traf_util_jar
+    $PDSH_HADOOP_NODES rm $LOCAL_WORKDIR/$hbase_trx_jar 2>/dev/null
+    $PDSH_HADOOP_NODES rm $LOCAL_WORKDIR/$traf_util_jar 2>/dev/null
 else
     for node in $HADOOP_NODES
     do
@@ -119,43 +121,58 @@ sudo chmod 777 $HOME/hbase-site.xml
 sudo cp $HOME/hbase-site.xml $TRAF_WORKDIR
 sudo chown trafodion.trafodion $TRAF_WORKDIR/hbase-site.xml
 
-sudo su $HDFS_USER --command "hadoop fs -mkdir /hbase-staging" 2> $HOME/traf_temp_output
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -mkdir /hbase-staging" 2> $HOME/traf_temp_output
 if [ $? != 0 ]; then
    # ok if directory already exists
    dir_exists=$(grep "File exists" $HOME/traf_temp_output | wc -l)
    if [ $dir_exists -eq 0 ]; then
-      echo "***ERROR: 'hadoop fs -mkdir /hbase-staging' command failed"
+      echo "***ERROR: '$HADOOP_BIN_PATH/hadoop fs -mkdir /hbase-staging' command failed"
       echo "***ERROR: $(cat $HOME/traf_temp_output)"
       exit -1
    fi
 fi
 
-sudo su $HDFS_USER --command "hadoop fs -chown -R $HBASE_USER:$HBASE_GROUP /hbase-staging"
-sudo su $HDFS_USER --command "hadoop fs -mkdir /bulkload" 2> $HOME/traf_temp_output
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -chown -R $HBASE_USER:$HBASE_GROUP /hbase-staging"
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -mkdir /bulkload" 2> $HOME/traf_temp_output
 if [ $? != 0 ]; then
    # ok if directory already exists
    dir_exists=$(grep "File exists" $HOME/traf_temp_output | wc -l)
    if [ $dir_exists -eq 0 ]; then
-      echo "***ERROR: 'hadoop fs -mkdir /bulkload' command failed"
+      echo "***ERROR: '$HADOOP_BIN_PATH/hadoop fs -mkdir /bulkload' command failed"
       echo "***ERROR: $(cat $HOME/traf_temp_output)"
       exit -1
    fi
 fi
-sudo su $HDFS_USER --command "hadoop fs -chown -R $TRAF_USER:trafodion /bulkload"
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -chown -R $TRAF_USER:trafodion /bulkload"
 
 # Create lobs directory
-sudo su $HDFS_USER --command "hadoop fs -mkdir /lobs" 2> $HOME/traf_temp_output
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -mkdir /lobs" 2> $HOME/traf_temp_output
 if [ $? != 0 ]; then
    # ok if directory already exists
    dir_exists=$(grep "File exists" $HOME/traf_temp_output | wc -l)
    if [ $dir_exists -eq 0 ]; then
-      echo "***ERROR: 'hadoop fs -mkdir /lobs' command failed"
+      echo "***ERROR: '$HADOOP_BIN_PATH/hadoop fs -mkdir /lobs' command failed"
       echo "***ERROR: $(cat $LOCAL_WORKDIR/traf_temp_output)"
       exit -1
    fi
 fi
-sudo su $HDFS_USER --command "hadoop fs -chown -R $TRAF_USER:trafodion /lobs"
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -chown -R $TRAF_USER:trafodion /lobs"
 
+
+#Create Backup directory 
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -mkdir /trafodion_backups" 2> $HOME/traf_temp_output
+if [ $? != 0 ]; then
+   # ok if directory already exists
+   dir_exists=$(grep "File exists" $HOME/traf_temp_output | wc -l)
+   if [ $dir_exists -eq 0 ]; then
+      echo "***ERROR: '$HADOOP_BIN_PATH/hadoop fs -mkdir /trafodion_backups' command failed"
+      echo "***ERROR: $(cat $LOCAL_WORKDIR/traf_temp_output)"
+      exit -1
+   fi
+fi
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -chown -R $TRAF_USER:trafodion /trafodion_backups"
+
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -chmod 777 /trafodion_backups"
 #=====================================
 # Modify hadoop settings as needed by Trafodion
 
@@ -327,35 +344,35 @@ echo "***INFO: Hadoop restart completed successfully"
 
 # wait to make sure HDFS is fully restarted and out of safemode
 echo "***INFO: waiting for HDFS to exit safemode"
-sudo su hdfs --command "hdfs dfsadmin -safemode wait"
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfsadmin -safemode wait"
 
 #====================================================
 # NOTE: These command must be done AFTER acls are 
 #       enabled and HDFS has been restarted
 echo "***INFO: Setting HDFS ACLs for snapshot scan support"
-sudo su hdfs --command "hdfs dfs -mkdir -p /hbase/archive"
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfs -mkdir -p /hbase/archive"
 if [ $? != 0 ]; then
-   echo "***ERROR: (hdfs dfs -mkdir -p /hbase/archive) command failed"
+   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -mkdir -p /hbase/archive) command failed"
    exit -1
 fi
-sudo su hdfs --command "hdfs dfs -chown hbase:hbase /hbase/archive"
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfs -chown hbase:hbase /hbase/archive"
 if [ $? != 0 ]; then
-   echo "***ERROR: (hdfs dfs -chown hbase:hbase /hbase/archive) command failed"
+   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -chown hbase:hbase /hbase/archive) command failed"
    exit -1
 fi
-sudo su hdfs --command "hdfs dfs -setfacl -R -m user:$TRAF_USER:rwx /hbase/archive"
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m user:$TRAF_USER:rwx /hbase/archive"
 if [ $? != 0 ]; then
-   echo "***ERROR: (hdfs dfs -setfacl -R -m user:$TRAF_USER:rwx /hbase/archive) command failed"
+   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m user:$TRAF_USER:rwx /hbase/archive) command failed"
    exit -1
 fi
-sudo su hdfs --command "hdfs dfs -setfacl -R -m default:user:$TRAF_USER:rwx /hbase/archive"
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m default:user:$TRAF_USER:rwx /hbase/archive"
 if [ $? != 0 ]; then
-   echo "***ERROR: (hdfs dfs -setfacl -R -m default:user:$TRAF_USER:rwx /hbase/archive) command failed"
+   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m default:user:$TRAF_USER:rwx /hbase/archive) command failed"
    exit -1
 fi
-sudo su hdfs --command "hdfs dfs -setfacl -R -m mask::rwx /hbase/archive"
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m mask::rwx /hbase/archive"
 if [ $? != 0 ]; then
-   echo "***ERROR: (hdfs dfs -setfacl -R -m mask::rwx /hbase/archive) command failed"
+   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m mask::rwx /hbase/archive) command failed"
    exit -1
 fi
 
diff --git a/install/installer/traf_hortonworks_mods98 b/install/installer/traf_hortonworks_mods98
--- a/install/installer/traf_hortonworks_mods98
+++ b/install/installer/traf_hortonworks_mods98
@@ -33,9 +33,8 @@ export PDSH="pdsh -R exec"
 export PDSH_SSH_CMD="ssh -q -n %h"
 export PDCP="pdcp -R ssh"
 
-TRAF_PDCP="$PDCP $MY_NODES"
-TRAF_PDSH="$PDSH $MY_NODES $PDSH_SSH_CMD"
-
+export PDSH_HADOOP_NODES="$PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD"
+export PDCP_HADOOP_NODES="$PDCP $MY_HADOOP_NODES"
 #=====================================
 # copy Trafodion hbase trx jar to /usr/lib/hbase/lib
 
@@ -82,26 +81,26 @@ fi
 # if more than one node then copy to all nodes
 echo "***INFO: copying $hbase_trx_jar to all nodes"
 if [ $node_count -ne 1 ]; then
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo rm -rf  $HADOOP_PATH/hbase-trx* 2>/dev/null
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo rm -rf /usr/lib/hbase/lib/hbase-trx* 2>/dev/null
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo rm -rf /usr/hdp/current/hbase-regionserver/lib/hbase-trx* 2>/dev/null
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo rm -rf /usr/share/cmf/lib/plugins/hbase-trx* 2>/dev/null
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo rm -rf /usr/lib/hbase/lib/trafodion* 2>/dev/null
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo rm -rf /usr/hdp/current/hbase-regionserver/lib/trafodion* 2>/dev/null
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo rm -rf /usr/share/cmf/lib/plugins/trafodion* 2>/dev/null
-    $PDSH $MY_NODES $PDSH_SSH_CMD mkdir -p $LOCAL_WORKDIR 2>/dev/null
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD mkdir -p $LOCAL_WORKDIR 2>/dev/null
+    $PDSH_HADOOP_NODES sudo rm -rf  $HADOOP_PATH/hbase-trx* 2>/dev/null
+    $PDSH_HADOOP_NODES sudo rm -rf /usr/lib/hbase/lib/hbase-trx* 2>/dev/null
+    $PDSH_HADOOP_NODES sudo rm -rf /usr/hdp/current/hbase-regionserver/lib/hbase-trx* 2>/dev/null
+    $PDSH_HADOOP_NODES sudo rm -rf /usr/share/cmf/lib/plugins/hbase-trx* 2>/dev/null
+    $PDSH_HADOOP_NODES sudo rm -rf /usr/lib/hbase/lib/trafodion* 2>/dev/null
+    $PDSH_HADOOP_NODES sudo rm -rf /usr/hdp/current/hbase-regionserver/lib/trafodion* 2>/dev/null
+    $PDSH_HADOOP_NODES sudo rm -rf /usr/share/cmf/lib/plugins/trafodion* 2>/dev/null
+    $TRAF_PDSH mkdir -p $LOCAL_WORKDIR 2>/dev/null
+    $PDSH_HADOOP_NODES mkdir -p $LOCAL_WORKDIR 2>/dev/null
     cp $UNTAR_DIR/export/lib/$hbase_trx_jar $LOCAL_WORKDIR
     cp $UNTAR_DIR/export/lib/$traf_util_jar $LOCAL_WORKDIR
-    $PDCP $MY_HADOOP_NODES $LOCAL_WORKDIR/$hbase_trx_jar $LOCAL_WORKDIR
-    $PDCP $MY_HADOOP_NODES $LOCAL_WORKDIR/$traf_util_jar $LOCAL_WORKDIR
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo cp $LOCAL_WORKDIR/$traf_util_jar $HADOOP_PATH
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo cp $LOCAL_WORKDIR/$hbase_trx_jar $HADOOP_PATH
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo chmod 644 $HADOOP_PATH/$hbase_trx_jar
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo chmod 644 $HADOOP_PATH/$traf_util_jar
+    $PDCP_HADOOP_NODES $LOCAL_WORKDIR/$hbase_trx_jar $LOCAL_WORKDIR
+    $PDCP_HADOOP_NODES $LOCAL_WORKDIR/$traf_util_jar $LOCAL_WORKDIR
+    $PDSH_HADOOP_NODES sudo cp $LOCAL_WORKDIR/$traf_util_jar $HADOOP_PATH
+    $PDSH_HADOOP_NODES sudo cp $LOCAL_WORKDIR/$hbase_trx_jar $HADOOP_PATH
+    $PDSH_HADOOP_NODES sudo chmod 644 $HADOOP_PATH/$hbase_trx_jar
+    $PDSH_HADOOP_NODES sudo chmod 644 $HADOOP_PATH/$traf_util_jar
 
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD rm $LOCAL_WORKDIR/$hbase_trx_jar 2>/dev/null
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD rm $LOCAL_WORKDIR/$traf_util_jar 2>/dev/null
+    $PDSH_HADOOP_NODES rm $LOCAL_WORKDIR/$hbase_trx_jar 2>/dev/null
+    $PDSH_HADOOP_NODES rm $LOCAL_WORKDIR/$traf_util_jar 2>/dev/null
 else
     for node in $HADOOP_NODES
     do 
@@ -271,7 +270,7 @@ echo
 poll_time=30
 echo "***INFO: Restarting HBase to pick up config changes for Trafodion"
 echo "***INFO: Stopping HBase..."
-curl -u $ADMIN:$PASSWORD \
+curl -k -u $ADMIN:$PASSWORD \
     -H "X-Requested-By: Trafodion" \
     -X PUT -d '{"ServiceInfo": { "state" : "INSTALLED" }}' \
     $URL/api/v1/clusters/$CLUSTER_NAME/services/HBASE > $TRAF_WORKDIR/traf_hbase_restart_temp
@@ -298,7 +297,7 @@ echo "***DEBUG: Ambari command_id=$command_id"
 completed=0
 while [ $completed -eq 0 ]; do
     sleep $poll_time
-    curl -u $ADMIN:$PASSWORD \
+    curl -k -u $ADMIN:$PASSWORD \
         $URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
         > $LOCAL_WORKDIR/hbase_restart_status_temp
     cat $LOCAL_WORKDIR/hbase_restart_status_temp
@@ -313,7 +312,7 @@ echo "***INFO: HBase stop completed"
 #Stop Zookeeper
 
 echo "***INFO: Stopping Zookeeper..."
-curl --user $ADMIN:$PASSWORD \
+curl -k --user $ADMIN:$PASSWORD \
     -H "X-Requested-By: Trafodion" \
     -X PUT -d '{"ServiceInfo": { "state" : "INSTALLED" }}' \
     $URL/api/v1/clusters/$CLUSTER_NAME/services/ZOOKEEPER > $TRAF_WORKDIR/traf_zoo_restart_temp
@@ -340,7 +339,7 @@ echo "***DEBUG: Ambari command_id=$command_id"
 completed=0
 while [ $completed -eq 0 ]; do
     sleep $poll_time
-    curl --user $ADMIN:$PASSWORD \
+    curl -k --user $ADMIN:$PASSWORD \
         $URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
         > $LOCAL_WORKDIR/traf_zoo_restart_temp
     cat $LOCAL_WORKDIR/traf_zoo_restart_temp
@@ -354,7 +353,7 @@ done
 
 echo "***INFO: Restarting HDFS to pick up config changes for Trafodion"
 echo "***INFO: Stopping HDFS..."
-curl --user $ADMIN:$PASSWORD \
+curl -k --user $ADMIN:$PASSWORD \
     -H "X-Requested-By: Trafodion" \
     -X PUT -d '{"ServiceInfo": { "state" : "INSTALLED" }}' \
     $URL/api/v1/clusters/$CLUSTER_NAME/services/HDFS > $TRAF_WORKDIR/traf_hdfs_restart_temp
@@ -381,7 +380,7 @@ echo "***DEBUG: Ambari command_id=$command_id"
 completed=0
 while [ $completed -eq 0 ]; do
     sleep $poll_time
-    curl --user $ADMIN:$PASSWORD \
+    curl -k --user $ADMIN:$PASSWORD \
         $URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
         > $LOCAL_WORKDIR/traf_hdfs_restart_temp
     cat $LOCAL_WORKDIR/traf_hdfs_restart_temp
@@ -391,7 +390,7 @@ while [ $completed -eq 0 ]; do
 done
 
 echo "***INFO: Starting HDFS..."
-curl --user $ADMIN:$PASSWORD \
+curl -k --user $ADMIN:$PASSWORD \
     -H "X-Requested-By: Trafodion" \
     -X PUT -d '{"ServiceInfo": { "state" : "STARTED" }}' \
     $URL/api/v1/clusters/$CLUSTER_NAME/services/HDFS > $TRAF_WORKDIR/traf_hdfs_restart_temp
@@ -417,7 +416,7 @@ echo "***DEBUG: Ambari command_id=$command_id"
 completed=0
 while [ $completed -eq 0 ]; do
     sleep $poll_time
-    curl --user $ADMIN:$PASSWORD \
+    curl -k --user $ADMIN:$PASSWORD \
         $URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
         > $LOCAL_WORKDIR/traf_hdfs_restart_temp
     cat $LOCAL_WORKDIR/traf_hdfs_restart_temp
@@ -436,7 +435,7 @@ sudo su hdfs --command "hdfs dfsadmin -safemode wait"
 # Start Zookeeper to pick up all the changes just made
 
 echo "***INFO: Starting Zookeeper..."
-curl --user $ADMIN:$PASSWORD \
+curl -k --user $ADMIN:$PASSWORD \
     -H "X-Requested-By: Trafodion" \
     -X PUT -d '{"ServiceInfo": { "state" : "STARTED" }}' \
     $URL/api/v1/clusters/$CLUSTER_NAME/services/ZOOKEEPER > $TRAF_WORKDIR/traf_zoo_restart_temp
@@ -462,7 +461,7 @@ echo "***DEBUG: Ambari command_id=$command_id"
 completed=0
 while [ $completed -eq 0 ]; do
     sleep $poll_time
-    curl --user $ADMIN:$PASSWORD \
+    curl -k --user $ADMIN:$PASSWORD \
         $URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
         > $LOCAL_WORKDIR/traf_zoo_restart_temp
     cat $LOCAL_WORKDIR/traf_zoo_restart_temp
@@ -478,7 +477,7 @@ echo "***INFO: Zookeeper start completed"
 
 echo "***INFO: Restarting HBase to pick up config changes for Trafodion"
 echo "***INFO: Starting HBase..."
-curl -u $ADMIN:$PASSWORD \
+curl -k -u $ADMIN:$PASSWORD \
     -H "X-Requested-By: Trafodion" \
     -X PUT -d '{"ServiceInfo": { "state" : "STARTED" }}' \
     $URL/api/v1/clusters/$CLUSTER_NAME/services/HBASE > $TRAF_WORKDIR/traf_hbase_restart_temp
@@ -504,7 +503,7 @@ echo "***DEBUG: Ambari command_id=$command_id"
 completed=0
 while [ $completed -eq 0 ]; do
     sleep $poll_time
-    curl -u $ADMIN:$PASSWORD \
+    curl -k -u $ADMIN:$PASSWORD \
         $URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
         > $LOCAL_WORKDIR/hbase_restart_status_temp
     cat $LOCAL_WORKDIR/hbase_restart_status_temp
@@ -544,6 +543,32 @@ if [ $? != 0 ]; then
    echo "***ERROR: (hdfs dfs -setfacl -R -m mask::rwx /apps/hbase/data/archive) command failed"
    exit -1
 fi
+
+ssh -q -n $AMBARI_HOST 'sudo su hdfs --command "hdfs dfs -mkdir -p /apps/hbase/data/archive/data"'
+if [ $? != 0 ]; then
+   echo "***ERROR: (hdfs dfs -mkdir -p /apps/hbase/data/archive/data) command failed"
+   exit -1
+fi
+
+ssh -q -n $AMBARI_HOST 'sudo su hdfs --command "hdfs dfs -chown hbase:hdfs /apps/hbase/data/archive/data"'
+if [ $? != 0 ]; then
+   echo "***ERROR: (hdfs dfs -chown hbase:hdfs /apps/hbase/data/archive/data) command failed"
+   exit -1
+fi
+
+ssh -q -n $AMBARI_HOST 'sudo su hdfs --command "hdfs dfs -mkdir -p /apps/hbase/data/archive/data/default"'
+if [ $? != 0 ]; then
+   echo "***ERROR: (hdfs dfs -mkdir -p /apps/hbase/data/archive/data/default) command failed"
+   exit -1
+fi
+
+ssh -q -n $AMBARI_HOST 'sudo su hdfs --command "hdfs dfs -chown hbase:hdfs /apps/hbase/data/archive/data/default"'
+if [ $? != 0 ]; then
+   echo "***ERROR: (hdfs dfs -chown hbase:hdfs /apps/hbase/data/archive/data/default) command failed"
+   exit -1
+fi
+
+
 
 
 # clean up files generated by Ambari's config.sh script
