- STRConfig related changes
- Merge my updates from Ent 1.0

diff --git a/core/sqf/sql/scripts/add_peer b/core/sqf/sql/scripts/add_peer
--- a/core/sqf/sql/scripts/add_peer
+++ b/core/sqf/sql/scripts/add_peer
@@ -24,7 +24,7 @@ function Usage {
     echo
     echo "Usage: $0 {-i <nn> | -q <an,.>| -p <nn> | -h}"
     echo
-    echo "-i ID of the peer (A number greater than 0)"
+    echo "-i ID of the peer (A number between 1 and 100)"
     echo
     echo "-q Zookeeper quorum (comma-separated list of server names/IP addresses)"
     echo
@@ -66,6 +66,13 @@ do
     case $lv_arg in 
 	i)
 	    lv_peer_id=${OPTARG}
+	    if (
+		    [ $lv_peer_id -lt 1 ] ||
+		    [ $lv_peer_id -gt 100 ]
+		); then
+		echo "Please provide a peer id in the range 1-100"
+		exit 1
+	    fi
 	    ;;
 	
 	q)
@@ -93,7 +100,7 @@ fi
 
 if [ $lv_peer_id -lt 1 ]; then
     echo
-    echo "Error: The Peer ID should be greater than 0"
+    echo "Error: The peer id should be in the range 1-100"
     Usage
     exit 1
 fi
@@ -132,6 +139,10 @@ cat <<EOF > ${lv_hbase_site_xml}
   <property>
     <name>hbase.zookeeper.property.clientPort</name>
     <value>${lv_zookeeper_port}</value>
+  </property>
+  <property>
+    <name>esgyn.cluster.id</name>
+    <value>${lv_peer_id}</value>
   </property>
 </configuration>
 EOF
